{{- range $.Values.environmentsInternalNames }}
---
apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ $.Values.accountID }}:role/{{ $.Values.clusterName }}-secret-role-{{ . }}
    privatecloud.mendix.com/environment-account: "true"
  name: {{ . }}
  namespace: mendix
{{- end }}